### ISSUE TITLE
Grimoire of Gaia

### ISSUE THREAD

**Issue by Fortist** [davidmaamoaix/TinyMobFarm#1]
It seems because of a loot table issue you cant capture GoG mobs with the lasso, or at least the Minotaur

```
---- Minecraft Crash Report ----
// Ooh. Shiny.

Time: 2019-02-23 08:02:36 EST
Description: Error executing task

java.util.concurrent.ExecutionException: net.minecraftforge.fml.relauncher.ReflectionHelper$UnableToFindMethodException: java.lang.NoSuchMethodException: gaia.entity.monster.EntityGaiaMinotaur.func_184647_J()
    at java.util.concurrent.FutureTask.report(Unknown Source)
    at java.util.concurrent.FutureTask.get(Unknown Source)
    at net.minecraft.util.Util.runTask(SourceFile:531)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:723)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:185)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Unknown Source)
Caused by: net.minecraftforge.fml.relauncher.ReflectionHelper$UnableToFindMethodException: java.lang.NoSuchMethodException: gaia.entity.monster.EntityGaiaMinotaur.func_184647_J()
    at net.minecraftforge.fml.relauncher.ReflectionHelper.findMethod(ReflectionHelper.java:303)
    at cn.davidma.tinymobfarm.util.LootTableHelper.getLootTableLocation(LootTableHelper.java:27)
    at cn.davidma.tinymobfarm.item.Lasso.interactEntity(Lasso.java:66)
    at cn.davidma.tinymobfarm.item.template.InteractiveMobTool.itemInteractionForEntity(InteractiveMobTool.java:61)
    at net.minecraft.item.ItemStack.interactWithEntity(ItemStack.java:391)
    at net.minecraft.entity.player.EntityPlayer.interactOn(EntityPlayer.java:1220)
    at com.tmtravlr.potioncore.network.PacketHandlerServer.useEntity(PacketHandlerServer.java:96)
    at com.tmtravlr.potioncore.network.PacketHandlerServer.lambda$onMessage$1(PacketHandlerServer.java:66)
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
    at java.util.concurrent.FutureTask.run(Unknown Source)
    at net.minecraft.util.Util.runTask(SourceFile:529)
    ... 5 more
Caused by: java.lang.NoSuchMethodException: gaia.entity.monster.EntityGaiaMinotaur.func_184647_J()
    at java.lang.Class.getDeclaredMethod(Unknown Source)
    at net.minecraftforge.fml.relauncher.ReflectionHelper.findMethod(ReflectionHelper.java:297)
    ... 15 more
```
1.12, btw.

**Comment by WenXin20** [comment]
I got this crash, but with Aether II, Quark, and Extra Golems mobs, it seems to happen with modded mobs.

**Comment by linxuanm** [comment]
Reflection's problem. Will be fixed in next version.

**Comment by linxuanm** [comment]
Fixed. Will publish to CurseForge after some final fixes. Issue closed.
