### ISSUE TITLE
not work for server

### ISSUE THREAD

**Issue by ikarosu** [davidmaamoaix/TinyMobFarm#4]
[23:45:43.970] [Server thread/ERROR] [javafmlmod.FMLModContainer/LOADING]: Failed to load class cn.davidma.tinymobfarm.common.TinyMobFarm
java.lang.RuntimeException: Attempted to load class net/minecraft/client/gui/GuiScreen for invalid dist DEDICATED_SERVER
at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClass(RuntimeDistCleaner.java:67) ~[forge-1.13.2-25.0.79.jar:25.0]
at cpw.mods.modlauncher.LaunchPluginHandler.lambda$offerClassNodeToPlugins$7(LaunchPluginHandler.java:40) ~[modlauncher-0.12.1.jar:?]
at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:1.8.0_201]
at java.util.stream.ReferencePipeline$11$1.accept(Unknown Source) ~[?:1.8.0_201]
at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_201]
at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_201]
at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_201]
at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:1.8.0_201]
at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_201]
at java.util.stream.ReferencePipeline.reduce(Unknown Source) ~[?:1.8.0_201]
at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:41) ~[modlauncher-0.12.1.jar:?]
at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:90) ~[modlauncher-0.12.1.jar:?]
at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:214) ~[modlauncher-0.12.1.jar:?]
at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:76) ~[modlauncher-0.12.1.jar:?]
at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.loadClass(TransformingClassLoader.java:169) ~[modlauncher-0.12.1.jar:?]
at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_201]
at java.lang.Class.forName0(Native Method) ~[?:1.8.0_201]
at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_201]
at net.minecraftforge.fml.javafmlmod.FMLModContainer.<init>(FMLModContainer.java:70) ~[?:25.0]
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_201]
at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_201]
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_201]
at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_201]
at net.minecraftforge.fml.javafmlmod.FMLJavaModLanguageProvider$FMLModTarget.loadMod(FMLJavaModLanguageProvider.java:73) ~[?:25.0]
at net.minecraftforge.fml.ModLoader.buildModContainerFromTOML(ModLoader.java:179) ~[?:?]
at net.minecraftforge.fml.ModLoader.lambda$buildMods$6(ModLoader.java:169) ~[?:?]
at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:1.8.0_201]
at java.util.HashMap$EntrySpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_201]
at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_201]
at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_201]
at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:1.8.0_201]
at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_201]
at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:1.8.0_201]
at net.minecraftforge.fml.ModLoader.buildMods(ModLoader.java:169) ~[?:?]
at net.minecraftforge.fml.ModLoader.lambda$loadMods$2(ModLoader.java:128) ~[?:?]
at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) [?:1.8.0_201]
at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) [?:1.8.0_201]
at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) [?:1.8.0_201]
at java.util.stream.AbstractPipeline.copyInto(Unknown Source) [?:1.8.0_201]
at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) [?:1.8.0_201]
at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) [?:1.8.0_201]
at java.util.stream.AbstractPipeline.evaluate(Unknown Source) [?:1.8.0_201]
at java.util.stream.ReferencePipeline.collect(Unknown Source) [?:1.8.0_201]
at net.minecraftforge.fml.ModLoader.loadMods(ModLoader.java:130) [?:?]
at net.minecraftforge.fml.server.ServerModLoader.begin(ServerModLoader.java:43) [?:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:116) [?:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:549) [?:?]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]

**Comment by linxuanm** [comment]
1. Provide the entire crash log.
2. Also specify the version of the mod you are using as well as the Minecraft version.

**Comment by linxuanm** [comment]
Fixed.
